/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jni_udt_JniUDT */

#ifndef _Included_com_jni_udt_JniUDT
#define _Included_com_jni_udt_JniUDT
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jni_udt_JniUDT
 * Method:    startup
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jni_udt_JniUDT_startup
  (JNIEnv *, jobject);

/*
 * Class:     com_jni_udt_JniUDT
 * Method:    cleanup
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jni_udt_JniUDT_cleanup
  (JNIEnv *, jobject);

/*
 * Class:     com_jni_udt_JniUDT
 * Method:    socket
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jni_udt_JniUDT_socket
  (JNIEnv *, jobject);

/*
 * Class:     com_jni_udt_JniUDT
 * Method:    connect
 * Signature: (ILjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_jni_udt_JniUDT_connect
  (JNIEnv *, jobject, jint, jstring, jint);

/*
 * Class:     com_jni_udt_JniUDT
 * Method:    close
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_jni_udt_JniUDT_close
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_jni_udt_JniUDT
 * Method:    send
 * Signature: (I[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_jni_udt_JniUDT_send
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_jni_udt_JniUDT
 * Method:    recv
 * Signature: (I[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_jni_udt_JniUDT_recv
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_jni_udt_JniUDT
 * Method:    bind
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_jni_udt_JniUDT_bind
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_jni_udt_JniUDT
 * Method:    listen
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_jni_udt_JniUDT_listen
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_jni_udt_JniUDT
 * Method:    accept
 * Signature: (I)Lcom/jni/udt/AcceptResult;
 */
JNIEXPORT jobject JNICALL Java_com_jni_udt_JniUDT_accept
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
